---
- name: Install Nginx, Python3, Docker on Amazon Linux
  hosts: amazon_linux
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Install Python 3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure pip-installed docker-compose (optional)
      pip:
        name: docker-compose
        executable: pip3
        state: present